### ISSUE TITLE
AppArmor can't start under Debian 8

### ISSUE THREAD

**Issue by pchaigno** [awailly/cis-ubuntu-ansible#22] opened 2015-05-19 12:35 UTC
Under Debian 64bit 8.0.0 in a VM:

```
TASK: [cis | 4.5 Activate AppArmor (start) (Scored)] ************************** 
failed: [127.0.0.1] => {"failed": true}
msg: Job for apparmor.service failed. See 'systemctl status apparmor.service' and 'journalctl -xn' for details.


FATAL: all hosts have already failed -- aborting
```

```
$ systemctl status apparmor.service
● apparmor.service - LSB: AppArmor initialization
   Loaded: loaded (/etc/init.d/apparmor)
   Active: failed (Result: exit-code) since Tue 2015-05-19 14:04:11 CEST; 26min ago
  Process: 3296 ExecStart=/etc/init.d/apparmor start (code=exited, status=1/FAILURE)
```

Could be the same issue as #10.

**Comment by awailly** [comment] 2015-05-19 13:29
Can you provide the reason of the failed start? Is level 1 OK?

**Comment by sabriedd** [comment] 2015-05-21 17:19
That one was tricky :)

actually, the error was : 

```
apparmor.service: control process exited, code=exited status=123
Failed to start LSB: AppArmor initialization.
Unit apparmor.service entered failed state.
```

 or in short  `apparmor not availble as kernel LSM`

In Debian 8 Jessie : 

``` bash
vim /etc/default/grub
GRUB_CMDLINE_LINUX=apparmor="1 security=apparmor"
```

In Debian 7 Wheezy : 

``` bash
vim /etc/default/grub
 GRUB_CMDLINE_LINUX_DEFAULT="security=apparmor quiet"
```

Finally : 

```
sudo update-grub
sudo reboot
[...]
sudo service apparmor start
sudo aa-status
apparmor module is loaded
42 profiles are loaded
```

So, maybe tomorrow i'll change the ansible task and check the distro version and make some modification accordingly

**Comment by pchaigno** [comment] 2015-05-22 12:15
I followed the steps for Debian 8. I get the following error:

```
TASK: [cis | 4.5 Activate AppArmor (Scored)] ********************************** 
failed: [127.0.0.1] => {"changed": false, "cmd": ["apparmor_status"], "delta": "0:00:00.070791", "end": "2015-05-22 14:13:48.967132", "failed": true, "failed_when_result": true, "rc": 0, "start": "2015-05-22 14:13:48.896341", "stdout_lines": ["apparmor module is loaded.", "4 profiles are loaded.", "4 profiles are in enforce mode.", "   /usr/lib/cups/backend/cups-pdf", "   /usr/sbin/cups-browsed", "   /usr/sbin/cupsd", "   /usr/sbin/cupsd//third_party", "0 profiles are in complain mode.", "2 processes have profiles defined.", "0 processes are in enforce mode.", "0 processes are in complain mode.", "2 processes are unconfined but have a profile defined.", "   /usr/sbin/cups-browsed (494) ", "   /usr/sbin/cupsd (493) "], "warnings": []}
stdout: apparmor module is loaded.
4 profiles are loaded.
4 profiles are in enforce mode.
   /usr/lib/cups/backend/cups-pdf
   /usr/sbin/cups-browsed
   /usr/sbin/cupsd
   /usr/sbin/cupsd//third_party
0 profiles are in complain mode.
2 processes have profiles defined.
0 processes are in enforce mode.
0 processes are in complain mode.
2 processes are unconfined but have a profile defined.
   /usr/sbin/cups-browsed (494) 
   /usr/sbin/cupsd (493) 

FATAL: all hosts have already failed -- aborting
```

**Comment by awailly** [comment] 2015-05-22 12:26
It looks like another issue. Manually restarting the cups service answer the question ? If yes, and given we already explained how to solve the issue in https://github.com/awailly/cis-ubuntu-ansible/issues/7#issuecomment-102357799, we have to update the documentation to solve such errors @paskl47.

**Comment by awailly** [comment] 2015-07-27 15:17
Not fully fixed, I only added documentation but @SpoonBoy did not patch the code. Waiting for the original fix.

**Comment by awailly** [comment] 2015-07-27 15:32
The very same bug is present on Debian 7.0.

**Comment by sabriedd** [comment] 2015-07-28 09:34
I would rather go for a " won't fix " ... as said in the repository title, it is intended to be used on **Ubuntu** systems, and testing are actually done on Debian, so we're going to face many more issues like this. Working on those is a little bit time consuming and could be spent on other problems. We should avoid to scatter for now.

(And the bad news is that the Debian CIS ruleset is from 2007 ... without the same formatting.)

**Comment by awailly** [comment] 2015-07-28 09:38
Ok some news. The ubuntu config setup the boot config file with :

```
ubuntu@bug44:~$ grep -i apparmor /boot/config-3.13.0-58-generic 
CONFIG_SECURITY_APPARMOR=y
CONFIG_SECURITY_APPARMOR_BOOTPARAM_VALUE=1
# CONFIG_SECURITY_APPARMOR_STATS is not set
CONFIG_SECURITY_APPARMOR_UNCONFINED_INIT=y
CONFIG_SECURITY_APPARMOR_HASH=y
CONFIG_DEFAULT_SECURITY_APPARMOR=y
CONFIG_DEFAULT_SECURITY="apparmor"
```

while debian is:

```
debian@boula:~$ grep -i apparmor /boot/config-3.16.0-4-amd64 
CONFIG_SECURITY_APPARMOR=y
CONFIG_SECURITY_APPARMOR_BOOTPARAM_VALUE=1
CONFIG_SECURITY_APPARMOR_HASH=y
# CONFIG_DEFAULT_SECURITY_APPARMOR is not set
```

So we have to add kernel boot parameters `apparmor=1 security=apparmor` to set the default security apparmor. It is `grub` on ubuntu but `syslinux` `/boot/extlinux/extlinux.conf` on debian (and `/extlinux.conf`).

The modification can be checked with the `/proc/cmdline` file :

```
debian@boula:~$ cat /proc/cmdline 
BOOT_IMAGE=boot/vmlinuz-3.16.0-4-amd64 initrd=boot/initrd.img-3.16.0-4-amd64 root=/dev/vda1 console=tty0 console=ttyS0,115200 ro quiet
```

to 

```
debian@boula:~$ cat /proc/cmdline 
BOOT_IMAGE=boot/vmlinuz-3.16.0-4-amd64 initrd=boot/initrd.img-3.16.0-4-amd64 root=/dev/vda1 console=tty0 console=ttyS0,115200 apparmor=1 security=apparmor ro quiet
```

**Comment by awailly** [comment] 2015-07-28 13:16
I think the problem is more general than Ubuntu vs Debian, but more that we are only supporting grub to add kernel boot options. The good way to solve it is to make a separate test case for each.
- [ ] Add the information in the documentation for apparmor @paskl47 
- [x] Syslinux support @SpoonBoy 
  - [x] Add a specific test to stop if both CONFIG_DEFAULT_SECURITY_APPARMOR and grub are not present
  - [x] Or add specific syslinux support

We will have the problem with other bootloaders.

**Comment by nagthgr8** [comment] 2016-01-05 07:54
Rebooting after adding this line GRUB_CMDLINE_LINUX=apparmor="1 security=apparmor"  has stopped my debian 8 to work, I had to undo above change for the system to function.

Maybe the later solution by @awailly would work but I prefer not to have apparmor installed on my linux rather trying not so safe methods

**Comment by awailly** [comment] 2016-01-05 08:26
Can you specify the lines you had to remove? It will definitely help others when encountering the exact same issue.

Did you try to set the use_apparmor to False? It may be more close to your expected environment, and should do the same as removing #55. If you tried and had a non functional system due to apparmor, we definitely need the logs to improve the option.

**Comment by awailly** [comment] 2016-01-13 11:58
The issue seems to be addressed by both the use_apparmor answer, and fix explained in https://github.com/awailly/cis-ubuntu-ansible/issues/22#issuecomment-125523227.

8 days auto resolve, will re-open when having answers from @nagthgr8.

**Closed as completed** 2016-01-13 11:58 UTC
Labels: bug, question

**Comment by kamrava** [comment] 2016-04-26 11:21
What about Ubuntu 16.04 ?
I have the same problem on Ubuntu 16.04

**Comment by awailly** [comment] 2016-04-26 12:25
Do you mind creating a new thread with your issue, what you tried in this thread, what is failing and how?
